### ISSUE TITLE
Need an image field in the show class

### ISSUE THREAD

**Issue by MRTZA** [WestwoodCompSci/SkippableTV_15.7#3]
GUI is still working on what type of object it will have to be for now it can just be an image.

**Comment by MRTZA** [comment]
Also the current problem we have is (if anyone can help to solve this it would be greatly appreciated):

to add an icon to a button it needs to be a component type
the image icon is not a component type and we cannot cast from image to component

**Comment by wesclock777** [comment]
this: Image img;
Imageicon icon = new ImageIcon(img);

**Comment by lekro** [comment]
You cannot instantiate an Image, and in that example, you will get a NPE
because img has not been initialized.

**Comment by wesclock777** [comment]
instantiate image? just use Image img= ImageIO.read(source);

**Comment by lekro** [comment]
^^ ah ok - that clears up things. Thanks

**Comment by lekro** [comment]
btw - there are three methods in the Show class pertaining to images:

`setImage(Image image)` - sets the image to `image`.
`readImage(String source)` - reads the image from `source`. Throws an `IOException` if the source is not found, or invalid.
`getImage()` - returns the image.
